---
name: schedule RPM builds
on:
  #schedule:
  #  # * is a special character in YAML so you have to quote this string
  #  - cron:  '55 20 * * *'
  
  push:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      ref:
        description: 'branch ref'
        required: true
        default: 'master'
      timestamp:
        description: 'timestamp identifier'
        required: true
      branch:
        description: 'branch name'
        default: 'master'
        required: false

jobs:
  rpmbuild_el7:
    name: Build an EL7 rpm
    runs-on: ubuntu-latest
    steps:
      - name: checkout code tree
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{github.event.inputs.branch}}

      - name: Run the build in a container (SL7/HEPCloud-CI)
        uses: ./.github/actions/python-command-in-sl7-container
        with:
          python-command: 'setup.py bdist_rpm'
          logfile: 'rpmbuild.log'

      - name: Archive rpm
        uses: actions/upload-artifact@v2
        with:
          name: rpms-DE-${{github.event.inputs.branch}}-${{github.event.inputs.timestamp}}
          path: dist/*.rpm
          if-no-files-found: error
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          
      - name: print Name Variables
        run: |
          echo "upload_url ${{ steps.create_release.outputs.upload_url }}"
          pwd
          ls dist
          
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/*.rpm
          asset_content_type: application/octet-stream
